runtime: python37
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  secure: always
  script: auto

- url: /static
  static_dir: static

env_variables:
  FIREBASE_PROJECT_ID: 'hackaz-265516'
  CLOUD_SQL_USERNAME: 'root'
  CLOUD_SQL_PASSWORD: 'cluivilab'
  CLOUD_SQL_DATABASE_NAME: 'hackaz_db'
  CLOUD_SQL_CONNECTION_NAME: 'hackaz-265516:us-west1:hackaz'